from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List
from enum import Enum

class EntityType(str, Enum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"
    LOCATION = "LOCATION"
    CONCEPT = "CONCEPT"
    EVENT = "EVENT"
    PRODUCT = "PRODUCT"
    UNKNOWN = "UNKNOWN"

# Models for the LLM to output (No IDs generated by LLM)
class RawEntity(BaseModel):
    name: str = Field(..., description="The name of the entity as it appears in text")
    type: EntityType = Field(..., description="The type of the entity")

class RawRelationship(BaseModel):
    source_entity_name: str = Field(..., description="The exact name of the source entity")
    target_entity_name: str = Field(..., description="The exact name of the target entity")
    relationship_type: str = Field(..., description="The type of the relationship (e.g., CREATED, WORKS_FOR, LOCATED_IN, PART_OF, MEMBER_OF, USES, DEPENDS_ON, REFERENCES, OWNS, RELATED_TO)")
    confidence: float = Field(..., description="Confidence score between 0.0 and 1.0")
    evidence: str = Field(..., description="The supporting text snippet from the chunk")

class RawGraphExtraction(BaseModel):
    entities: List[RawEntity] = Field(default_factory=list, description="List of extracted entities")
    relationships: List[RawRelationship] = Field(default_factory=list, description="List of extracted relationships")

# Final Normalized Models
class Entity(BaseModel):
    id: str = Field(..., description="Canonical ID for the entity")
    name: str = Field(..., description="The name of the entity")
    type: EntityType = Field(..., description="The type of the entity")
    properties: Dict[str, Any] = Field(default_factory=dict, description="Additional properties")

class Relationship(BaseModel):
    source: str = Field(..., description="The canonical ID of the source entity")
    target: str = Field(..., description="The canonical ID of the target entity")
    relationship_type: str = Field(..., description="The type of the relationship")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")
    evidence: str = Field(..., description="The supporting text snippet from the chunk")

class ExtractionMetadata(BaseModel):
    processing_time_ms: float = 0.0
    model_name: str = ""
    status: str = "SUCCESS"
    warnings: List[str] = Field(default_factory=list)

class GraphDocument(BaseModel):
    chunk_id: str
    document_id: str
    entities: List[Entity] = Field(default_factory=list)
    relationships: List[Relationship] = Field(default_factory=list)
    metadata: ExtractionMetadata = Field(default_factory=ExtractionMetadata)
